name: Deploy to AWS Lambda

on:
  pull_request:
      branches:
        - main

jobs:
  deploy_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies into build dir
        run: |
          mkdir -p build
          pip install -r requirements.txt -t build/
          cp -r app/ build/app/

      - name: Zip deployment package
        run: |
          cd build
          zip -r ../deployment.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name dollar_quote \
            --zip-file fileb://deployment.zip
